Remove dialog. Line based only

diff --git a/addimageencryption b/addimageencryption
--- a/addimageencryption
+++ b/addimageencryption
@@ -8,10 +8,6 @@ unset "${!LC_*}"
 LANG="C.utf8"
 export LANG
 
-# set to --keep-title to use altenate screen. Better for debugging but causes flicker
-dialog_altenate_screen=
-dialog_backtitle="Image Encryption Tool"
-interactive=
 verbose=
 nl=$'\n'
 
@@ -40,8 +36,6 @@ cleanup()
 }
 trap cleanup EXIT
 
-tmpfile="$tmpdir/tmp"
-
 helpandquit()
 {
 	cat <<-EOF
@@ -63,83 +57,35 @@ log_info()
 	echo "$@"
 }
 
-d(){
-	local retval=0
-	# Bash makes it a bit annoying to read the output of a different FD into a variable, it
-	# only supports reading stdout by itself. So redirect 3 to stdout and 1 to the real stdout.
-	exec {stdoutfd}>&1
-	result="$(dialog $dialog_altenate_screen --backtitle "$dialog_backtitle" --output-fd 3 "$@" 3>&1 1>&${stdoutfd})" || retval=$?
-	# Word splitting makes it necessary to use eval here.
-	eval "exec ${stdoutfd}>&-"
-	return "$retval"
-}
-
 err()
 {
-	if [ "$interactive" = 1 ]; then
-		d --title 'Error' --ok-label "Quit" --colors --aspect 60 --msgbox "\Z1Error:\Zn $*" 0 0
-	else
-		echo "Error: $*" >&2
-	fi
+	echo "Error: $*" >&2
 	exit 1
 }
 
 warn()
 {
-	if [ "$interactive" = 1 ]; then
-		d --title 'Warning' --ok-label "Continue" --colors --aspect 60 --msgbox "\Z1Warning:\Zn $*" 0 0
-	else
-		echo "Warning: $*" >&2
-	fi
+	echo "Warning: $*" >&2
 	exit 1
-}
-
-# Given the number of total item pairs, outputs the number of items to display at once
-menuheight() {
-	local height=$(($1 / 2))
-	[ "$height" -le "$dh_menu" ] || height="$dh_menu"
-	echo "$height"
-}
-
-stty_size() {
-	set -- $(stty size 2>/dev/null)
-	LINES="$1"
-	COLUMNS="$2"
-	# stty size can return zero when not ready or
-	# its a serial console
-	if [ "$COLUMNS" = "0" ] || [ "$LINES" = "0" ]; then
-		LINES=24
-		COLUMNS=80
-	fi
-
-	dh_menu=$((LINES-15))
-	dh_text=$((LINES-5))
-}
-
-fakereencrypt()
-{
-	while read -r line; do
-		read -r bytes size < <(echo "$line" | jq -r '[.device_bytes, .device_size]|join(" ")')
-		echo "$((bytes*100/size))"
-		usleep 500
-	done < p
 }
 
 isdigits()
 {
-	local v="${1:?}"
-	[ -z "${v//[0-9]*/}" ]
+       local v="${1:?}"
+       [ -z "${v//[0-9]*/}" ]
 }
 
-dialog_password()
+read_password()
 {
+	local password2
 	[ -z "$password" ] || return 0
         while true; do
-                d --insecure --passwordbox  $"Enter encryption password" 0 0
-                password="$result"
-                d --insecure --passwordbox  $"Confirm encryption password" 0 0
-                if [ "$password" != "$result" ]; then
-                        d --msgbox $"Entered passwords don't match" 5 40
+                read -r -s -p "Enter encryption passphrase: " password
+		echo
+                read -r -s -p "Confirm encryption passphrase: " password2
+		echo
+                if [ "$password" != "$password2" ]; then
+                        echo "Entered passwords don't match"
                         continue
                 fi
                 [ -n "$password" ] || err "No password, no encryption"
@@ -158,16 +104,13 @@ encrypt()
 
 ####### main #######
 
-stty_size
-
-getopttmp=$(getopt -o hc:v --long help,verbose,flicker -n "${0##*/}" -- "$@")
+getopttmp=$(getopt -o hc:v --long help,verbose -n "${0##*/}" -- "$@")
 eval set -- "$getopttmp"
 
 while true ; do
         case "$1" in
                 -h|--help) helpandquit ;;
 		-v|--verbose) verbose=$((++verbose)); shift ;;
-		--flicker) dialog_altenate_screen=--keep-tite; shift ;;
                 --) shift ; break ;;
                 *) echo "Internal error!" ; exit 1 ;;
         esac
@@ -201,7 +144,7 @@ eval "$(blkid -c /dev/null -o export "$looppart"|sed 's/^/loop_/')"
 [ "$loop_TYPE" != crypto_LUKS ] || err "Already encrypted"
 [ "$loop_TYPE" = btrfs ] || err "File system is $loop_TYPE but only btrfs is supported"
 
-dialog_password
+read_password
 
 log_info "mounting fs"
 mkdir -p "$tmpdir/mnt"
