Allow to abort encryption

diff --git a/addimageencryption-initrd b/addimageencryption-initrd
--- a/addimageencryption-initrd
+++ b/addimageencryption-initrd
@@ -12,5 +12,8 @@ elif getargbool 0 rd.encrypt || [ ! -e /sysroot/etc/machine-id ]; then
 	systemctl start sysroot.mount
 	# silence systemd
 	kill -SIGRTMIN+21 1
-	/usr/bin/addimageencryption -v --gen-key || die "Encryption failed"
+	echo -ne '\a'
+	read -n1 -s -r -t 5 -p "Press ESC to prevent encrypting the disk" inhibitor
+	echo
+	[ "$inhibitor" = $'\e' ] || /usr/bin/addimageencryption -v --gen-key || die "Encryption failed"
 fi
