Systemd-boot support and recovery key

diff --git a/addimageencryption-initrd b/addimageencryption-initrd
--- a/addimageencryption-initrd
+++ b/addimageencryption-initrd
@@ -4,10 +4,13 @@ type getarg > /dev/null 2>&1 || . /lib/dracut-lib.sh
 script=/run/combustion/mount/combustion/script
 if [ -e "$script" ] && grep -qE '^# combustion:(.*)\<encrypt\>' "$script"; then
 	systemctl start sysroot.mount
+	# silence systemd
+	kill -SIGRTMIN+21 1
 	chmod a+x "$script"
 	"$script" --encrypt
-else
+elif getargbool 0 rd.encrypt || [ ! -e /sysroot/etc/machine-id ]; then
 	systemctl start sysroot.mount
-	#/usr/bin/addimageencryption -v < /dev/console >/dev/console 2>&1 || die "Encryption failed"
-	/usr/bin/addimageencryption -v || die "Encryption failed"
+	# silence systemd
+	kill -SIGRTMIN+21 1
+	/usr/bin/addimageencryption -v --gen-key || die "Encryption failed"
 fi
