Name encrypted devices following the DPS document
Signed-off-by: Alberto Planas <aplanas@suse.com>

diff --git a/disk-encryption-tool-dracut b/disk-encryption-tool-dracut
--- a/disk-encryption-tool-dracut
+++ b/disk-encryption-tool-dracut
@@ -70,20 +70,20 @@ if [ "$encrypt" != "force" ]; then
 fi
 if [ "$inhibitor" != $'\e' ]; then
 	root_device="$(findmnt -nvo SOURCE /sysroot)"
-	root_cr_name="cr_root"
+	root_volume_name="root"
 	root_options="auto"
 	if get_credentials partitions disk-encryption-tool-dracut.partitions; then
 		for line in "${partitions[@]}"; do
-			read -r cr_name device options <<<"$line"
-			[ "$device" = "$root_device" ] && root_cr_name="$cr_name" && root_options="$options" && continue
+			read -r volume_name device options <<<"$line"
+			[ "$device" = "$root_device" ] && root_volume_name="$volume_name" && root_options="$options" && continue
 			echo "Encrypt $device"
-			/usr/bin/disk-encryption-tool --keyring cryptenroll --options "${options:-auto}" --root /sysroot "$device" "$cr_name" || die "Encryption failed"
+			/usr/bin/disk-encryption-tool --keyring cryptenroll --options "${options:-auto}" --root /sysroot "$device" "$volume_name" || die "Encryption failed"
 			clean_growpart_flag "$device"
 		done
 	fi
 	if [ "$root_options" != "skip" ]; then
 		echo "Encrypt /sysroot"
-		/usr/bin/disk-encryption-tool --keyring cryptenroll --options "${root_options:-auto}" "/sysroot" "$root_cr_name" || die "Encryption failed"
+		/usr/bin/disk-encryption-tool --keyring cryptenroll --options "${root_options:-auto}" "/sysroot" "$root_volume_name" || die "Encryption failed"
 		clean_growpart_flag "$root_device"
 	fi
 fi
